import services.calculations.mean_calculation
import services.calculations.detectDataSizes
import services.calculations.normalisation
import services.calculations.min_max
import services.calculations.quantile

