import Services.Calculations.quantile
import Services.Calculations.high_stimulus
import Services.Calculations.min_max
import Services.Calculations.detectDataSizes
import Services.Calculations.normalisation
import Services.Calculations.mean_calculation
